### ISSUE TITLE
is there support for node versions lower than 18?

### ISSUE THREAD

**Issue by steven4354** [paambaati/neon-js-sdk#4]
Hi, was wondering if the sdk would work for node versions lower than 18. I have a project that uses 16.17

Thanks!

**Comment by paambaati** [comment]
The 18.x compatibility requirement is primarily because this module uses native `fetch`.

It will work for you with the `—experimental-fetch` flag, as `fetch` was introduced in v16.15.0 — see https://nodejs.org/docs/latest-v16.x/api/globals.html#fetch

**Comment by paambaati** [comment]
This is also documented in https://github.com/paambaati/neon-js-sdk/commit/4532ec9d5b9da1f0e864a5327f31d236800a97f1.
